---

- name: Install JBOSS Common and EAP
  hosts: "{{ vm_name }}"
  gather_facts: true

  roles:
    
    - redhat-cop.jboss_eap

  collections:
    - ansible.posix

  tasks:

  - name: Install packages
    yum:
      name:
        - java-1.8.0-openjdk-devel
        - unzip
        - initscripts
        - python-pip
      state: present

  - name: Install python dependencies
    pip:
      name:
        - requests
        - lxml
      state: present


  
  - name: Open Firewalld for management port
    firewalld:
      port: 9990/tcp
      permanent: yes
      state: enabled 
    notify: restart_firewalld

  - name: Open Firewalld for http
    firewalld:
      port: 8080/tcp
      permanent: yes
      state: enabled 
    notify: restart_firewalld
    
  handlers:
    - name: restart_firewalld
      service:
        name: firewalld
        state: restarted