---
- name: Sync all PAH EE and Remote Repos
  hosts: localhost
  gather_facts: false
  become: false
  tags: sync

  roles:
    - sync_ee
    - sync_repos

- name: Build new EE
  hosts: ansibledev.shadowman.dev
  gather_facts: false
  tags: buildee

  roles:
    - build_ee
