---
dest_dir: /home/adworjan/ansible/execution/
pah_name: towerpah.shadowman.dev
image_name: shadowmanee
bindep_file: bindep.txt
python_requirements_file: requirements.txt
galaxy_requirements_file: requirements.yml
ee_base_image: registry.redhat.io/ansible-automation-platform/ee-minimal-rhel8:2.14
builder_image: registry.redhat.io/ansible-automation-platform-23/ansible-builder-rhel8:latest
ansible_config: ansible.cfg
galaxy_keyring: /home/adworjan/ansible/execution/fullkeyring.kbx
ee_bindep:
  - python3-jinja2 [platform:rpm]
  - which [platform:rpm]
  - git [platform:rpm]
ee_python:
  - scp
  - pyats
  - genie
ee_collections:
  - name: ansible.windows
  - name: community.windows
  - name: ansible.posix
  - name: vmware.vmware_rest
    version: 1.0.1
  - name: ansible.netcommon
  - name: ansible.utils
  - name: community.general
  - name: community.vmware
  - name: cloud.terraform
  - name: servicenow.itsm
  - name: vyos.vyos
  - name: cisco.ios
  - name: arista.eos
  - name: infra.osbuild
  - name: azure.azcollection
  - name: f5networks.f5_modules
  - name: citrix.adc
  - name: shadowman.reports
  - name: redhat.rhv
  - name: redhat.satellite
  - name: redhat.insights
  - name: ansible.controller
  - name: paloaltonetworks.panos
  - name: ibm.qradar
  - name: containers.podman
  - name: community.postgresql
ee_prepend:
  - ADD /sbin/terraform /sbin
ee_append:
  - COPY /certs/shadowman_cert.cer /certs/shadowman_cert.cer
  - COPY /certs/shadowman_private.key /certs/shadowman_private.key
  - COPY /certs/certificate.pfx /certs/certificate.pfx
  - COPY /certs/id_ed25519 /certs/id_ed25519
  - RUN git config --global user.email "adworjan@redhat.com"
  - RUN git config --global user.name "adworjan"
  - RUN git config --global core.sshCommand "ssh -i /certs/id_ed25519 -F /dev/null"
  - RUN microdnf reinstall tzdata -y
  - RUN git clone https://github.com/citrix/citrix-adc-ansible-modules.git /tmp/citrix
  - RUN pip3 install /tmp/citrix/deps/nitro-python-1.0_kamet.tar.gz
  - RUN rm -rf /tmp/citrix/
