---

- name: Sync Community Repo
  uri:
    url: https://towerpah.shadowman.dev/api/galaxy/content/community/v3/sync/
    user: "{{ pah_user }}"
    password: "{{ pah_pass }}"
    method: POST
    force_basic_auth: yes
    validate_certs: no

- name: Verify Community Repo Sync Completed
  uri:
    url: https://towerpah.shadowman.dev/api/galaxy/content/community/v3/sync/config/
    user: "{{ pah_user }}"
    password: "{{ pah_pass }}"
    validate_certs: no
    force_basic_auth: yes
  register: communitystatus
  until:  communitystatus.json.last_sync_task.state == "completed"
  retries: 80
  delay: 20
    
- name: Sync Certified Repo
  uri:
    url: https://towerpah.shadowman.dev/api/galaxy/content/rh-certified/v3/sync/
    user: "{{ pah_user }}"
    password: "{{ pah_pass }}"
    method: POST
    force_basic_auth: yes
    validate_certs: no

- name: Verify rh-certified Repo Sync Completed
  uri:
    url: https://towerpah.shadowman.dev/api/galaxy/content/rh-certified/v3/sync/config/
    user: "{{ pah_user }}"
    password: "{{ pah_pass }}"
    validate_certs: no
    force_basic_auth: yes
  register: certifiedstatus
  until:  certifiedstatus.json.last_sync_task.state == "completed"
  retries: 80
  delay: 20