---

- name: Sync Community Repo
  uri:
    url: https://towerpah.shadowman.dev/api/galaxy/content/community/v3/sync/
    user: "{{ pah_user }}"
    password: "{{ pah_pass }}"
    method: POST
    
- name: Sync Certified Repo
  uri:
    url: https://towerpah.shadowman.dev/api/galaxy/content/rh-certified/v3/sync/
    user: "{{ pah_user }}"
    password: "{{ pah_pass }}"
    method: POST

- name: Get Community Repo Status
  uri:
    url: https://towerpah.shadowman.dev/api/galaxy/content/community/v3/sync/config/
    user: "{{ pah_user }}"
    password: "{{ pah_pass }}"
  register: communitystatus

- name: Get rh-certified Repo Status
  uri:
    url: https://towerpah.shadowman.dev/api/galaxy/content/rh-certified/v3/sync/config/
    user: "{{ pah_user }}"
    password: "{{ pah_pass }}"
  register: certifiedstatus