---



- name: Get Community Repo Status
  uri:
    url: https://towerpah.shadowman.dev/api/galaxy/content/community/v3/sync/config/
    user: "{{ pah_user }}"
    password: "{{ pah_pass }}"
    validate_certs: no
    force_basic_auth: yes
  register: communitystatus

- name: Get rh-certified Repo Status
  uri:
    url: https://towerpah.shadowman.dev/api/galaxy/content/rh-certified/v3/sync/config/
    user: "{{ pah_user }}"
    password: "{{ pah_pass }}"
    validate_certs: no
    force_basic_auth: yes
  register: certifiedstatus