---
- name: Sync community repo
  redhat_cop.ah_configuration.ah_repository_sync:
    name: community
    wait: true

- name: Sync rh-certified repo
  redhat_cop.ah_configuration.ah_repository_sync:
    name: rh-certified
    wait: true