---

- name: Get current version
  ansible.builtin.slurp:
    src: '/home/adworjan/ansible/execution/version.txt'
  register: version

- name: get new tag version
  ansible.builtin.set_fact:
    new_version: "{{ (version['content'] | b64decode |float + 0.1)| round(1,'common') }}"

- name: overwrite version file
  ansible.builtin.copy:
    content: "{{ new_version }}\n"
    dest: /home/adworjan/ansible/execution/version.txt