---

- name: Get current version
  ansible.builtin.command:
    cmd: 'cat /home/adworjan/ansible/execution/version.txt'
  register: version

- name: get new tag version
  ansible.builtin.set_fact:
    new_version: "{{ version.stdout_lines[0] + 0.1 }}"

- name: new version
  ansible.builtin.debug:
    msg: "{{ new_version | round(1,'common') }}"

- name: overwrite version file
  ansible.builtin.copy:
    content: "{{ new_version | round(1,'common') }}\n"
    dest: /home/adworjan/ansible/execution/version.txt