---

- name: Add latest tag new
  redhat_cop.ah_configuration.ah_ee_image:
    name: full/ansibleee:1.1.0
    state: updated
    append: true
    tags:
      - newest
    ah_host: "{{ lookup('env', 'AH_HOST') }}"
    ah_username: "{{ lookup('env', 'pah_user') }}"
    ah_password: "{{ lookup('env', 'pah_pass') }}"