---

- name: Get current version
  ansible.builtin.slurp:
    src: '/home/adworjan/ansible/execution/version.txt'
  register: version

- name: output new version
  ansible.builtin.set_fact:
    current_version: "{{ version['content'] | b64decode |float + 0.1 }}"

- name: new version
  ansible.builtin.debug:
    msg: "{{ current_version }}"