
- name: Remove <none> images after build
  command:
    cmd: podman rmi $(podman images -f 'dangling=true')
  register: result
  changed_when: '"repository name must be" in result.stderr'

- name: push new EE to PAH
  command:
    cmd: "podman push --creds={{pah_user}}:{{pah_pass}} aaphub.shadowman.dev/full/ansibleee"
  changed_when: true