---

- name: Remove <none> images after build
  command:
    cmd: "podman rmi $(podman images -f 'dangling=true' -q)"
  changed_when: true

- name: push new EE to PAH
  command:
    cmd: "podman push --creds={{pah_user}}:{{pah_pass}} aaphub.shadowman.dev/full/ansibleee"
  changed_when: true