---
- name: Pull latest minimal EE
  ansible.builtin.command:
    cmd: "podman pull --creds={{ portaluser }}:{{ portalpassword }} registry.redhat.io/ansible-automation-platform-22/ee-minimal-rhel8:latest"
  changed_when: true
  ignore_errors: true

- name: Pull latest ansible-builder image
  ansible.builtin.command:
    cmd: "podman pull --creds={{ portaluser }}:{{ portalpassword }} registry.redhat.io/ansible-automation-platform-22/ansible-builder-rhel8:latest"
  changed_when: true
  ignore_errors: true

- name: Ensure old EE is removed
  ansible.builtin.command:
    cmd: "podman rmi towerpah.shadowman.dev/shadowmanee"
  changed_when: true
  ignore_errors: true

- name: Build new EE
  ansible.builtin.command:
    cmd: 'ansible-builder build -t towerpah.shadowman.dev/shadowmanee'
    chdir: /home/adworjan/ansible/execution/
  changed_when: true

- name: Remove <none> images after build
  ansible.builtin.shell:
    cmd: podman rmi $(podman images -f 'dangling=true' -q)
  changed_when: true

- name: Get current version
  ansible.builtin.slurp:
    src: '/home/adworjan/ansible/execution/version.txt'
  register: version

- name: get new tag version
  ansible.builtin.set_fact:
    new_version: "{{ (version['content'] | b64decode |float + 0.1)| round(1,'common') }}"

- name: overwrite version file
  ansible.builtin.copy:
    content: "{{ new_version }}\n"
    dest: /home/adworjan/ansible/execution/version.txt
    owner: root
    group: root
    mode: '0644'

- name: push new EE to PAH with version number
  ansible.builtin.command:
    cmd: "podman push --creds={{ pah_user }}:{{ pah_pass }} towerpah.shadowman.dev/shadowmanee towerpah.shadowman.dev/shadowmanee:{{ new_version }}.0"
  changed_when: true

- name: push new EE to PAH to get latest tag
  ansible.builtin.command:
    cmd: "podman push --creds={{ pah_user }}:{{ pah_pass }} towerpah.shadowman.dev/shadowmanee"
  changed_when: true

- name: Update Execution Environment Version in Controller with new version
  ansible.controller.execution_environment:
    name: "Automation Hub Default execution environment"
    image: "towerpah.shadowman.dev/shadowmanee:{{ new_version }}.0"
    validate_certs: no
    controller_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    controller_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    controller_host: "{{ lookup('env', 'TOWER_HOST') }}"
  delegate_to: localhost
