---

- name: Get current version
  ansible.builtin.slurp:
    src: '/home/adworjan/ansible/execution/version.txt'
  register: version

- name: output new version
  ansible.builtin.debug:
    msg: "{{ version['content'] | b64decode | int }}"