---

- name: Add latest tag
  redhat_cop.ah_configuration.ah_ee_image:
    name: full/ansibleee:1.1.0
    state: updated
    tags:
      - latest
    ah_host: "{{ lookup('env', 'AH_HOST') }}"
    ah_username: "{{ lookup('env', 'pah_user') }}"
    ah_password: a"{{ lookup('env', 'pah_pass') }}"
  delegate_to: towerpah.shadowman.dev