---

- name: Get current version
  ansible.builtin.slurp:
    src: '/home/adworjan/ansible/execution/version.txt'
  register: version

- name: get new tag version
  ansible.builtin.set_fact:
    new_version: "{{ version['content'] | b64decode |float + 0.1 }}"

- name: new version
  ansible.builtin.debug:
    msg: "{{ new_version }}"

- name: overwrite version file
  ansible.builtin.copy:
    content: "{{ new_version }}"
    dest: /home/adworjan/ansible/execution/version.txt