---
- name: Create new tag
  containers.podman.podman_tag:
    image: towerpah.shadowman.dev/shadowmanee
    target_names:
      - towerpah.shadowman.dev/shadowmanee:2.9.0

- name: Push new EE
  containers.podman.podman_image:
    name: towerpah.shadowman.dev/shadowmanee
    tag: "{{ item }}"
    push: true
    username: "{{ pah_user }}"
    password: "{{ pah_pass }}"
  loop:
    - "2.9.0"
    - latest

- name: Remove extra tag
  containers.podman.podman_image:
    name: towerpah.shadowman.dev/shadowmanee
    tag: 2.9.0
    state: absent
