---
- name: Pull builder images
  containers.podman.podman_image:
    name: "{{ item }}"
    username: "{{ portaluser }}"
    password: "{{ portalpassword }}"
    force: true
  loop:
    - registry.redhat.io/ansible-automation-platform-22/ee-minimal-rhel8
    - registry.redhat.io/ansible-automation-platform-22/ansible-builder-rhel8

- name: Delete old EE
  containers.podman.podman_image:
    name: towerpah.shadowman.dev/shadowmanee
    state: absent

- name: Build new EE
  ansible.builtin.command:
    cmd: 'ansible-builder build -t towerpah.shadowman.dev/shadowmanee --prune-images'
    chdir: /home/adworjan/ansible/execution/
  changed_when: true

- name: Get current version
  ansible.builtin.slurp:
    src: '/home/adworjan/ansible/execution/version.txt'
  register: version

- name: get new tag version
  ansible.builtin.set_fact:
    new_version: "{{ (version['content'] | b64decode |float + 0.1)| round(1,'common') }}"

- name: overwrite version file
  ansible.builtin.copy:
    content: "{{ new_version }}\n"
    dest: /home/adworjan/ansible/execution/version.txt
    owner: root
    group: root
    mode: '0644'

- name: Create new tag
  containers.podman.podman_tag:
    image: towerpah.shadowman.dev/shadowmanee
    target_names:
      - towerpah.shadowman.dev/shadowmanee:{{ new_version }}.0

- name: Push new EE
  containers.podman.podman_image:
    name: towerpah.shadowman.dev/shadowmanee
    tag: "{{ item }}"
    push: true
    username: "{{ pah_user }}"
    password: "{{ pah_pass }}"
  loop:
    - "{{ new_version }}.0"
    - latest

- name: Remove extra tag
  containers.podman.podman_image:
    name: towerpah.shadowman.dev/shadowmanee
    tag: "{{ new_version }}.0"
    state: absent

- name: Update Execution Environment Version in Controller with new version
  ansible.controller.execution_environment:
    name: "Automation Hub Default execution environment"
    image: "towerpah.shadowman.dev/shadowmanee:{{ new_version }}.0"
    validate_certs: false
    controller_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    controller_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    controller_host: "{{ lookup('env', 'TOWER_HOST') }}"
  delegate_to: localhost
