---

- name: Get current version
  ansible.builtin.set_fact:
    version: "{{ lookup('file', '/home/adworjan/ansible/execution/version.txt') | int}}"

- name: output new version
  ansible.builtin.debug:
    msg: "{{ version + 0.1 }}"